env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  indent: ['error', 4]
  new-cap: 'error'
  semi: ['error', 'always']
  quotes: ['error', 'single']
  no-var: 'error'
settings:
  react:
    version: 'detect'
