version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/mars/services/web/ui"
    schedule:
      interval: "monthly"
    labels:
      - "type: enhancement"
      - "mod: web"
      - "to be backported"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0

