---
engines:
  pylint:
    enabled: true
    python_version: 3
exclude_paths:
  - '.github'
  - 'bin'
  - 'docs'
  - 'mars/_version.py'
  - 'mars/lib'
  - 'mars/web/static'
  - 'misc'
  - 'versioneer.py'
  - '*.min.js'
  - '**/tests/**'
  - 'asv_bench/**'
