language: python

matrix:
  include:
    - sudo: required
      os: linux
      python: "2.7"
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp27-cp27mu
    - sudo: required
      os: linux
      python: "3.5"
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp35-cp35m
    - sudo: required
      os: linux
      python: "3.6"
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp36-cp36m
    - sudo: required
      os: linux
      python: "3.7"
      dist: xenial
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp37-cp37m
    - os: osx
      language: generic
      env: PYTHON=2.7.12
    - os: osx
      language: generic
      env: PYTHON=3.5.3
    - os: osx
      language: generic
      env: PYTHON=3.6.1
    - os: osx
      language: generic
      env: PYTHON=3.7.0

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source ./bin/travis-prepare-osx.sh; fi
  - pip install --upgrade pip setuptools wheel

# command to install dependencies
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements-extra.txt
  - pip install coveralls
  - python setup.py build_ext -i

# command to run tests
script:
  mkdir -p build &&
  pytest --cov-report= --cov-config .coveragerc-tensor --cov=mars --timeout=1500 mars/tensor &&
  mv .coverage build/.coverage.tensor.file &&
  pytest --cov-report= --cov-config .coveragerc --cov=mars --timeout=1500 --forked
    $(find mars -maxdepth 1 -mindepth 1 -type d -not -path "mars/tensor" -not -path "*__pycache__*") &&
  mv .coverage build/.coverage.main.file &&
  coverage combine build/ && coverage report --fail-under=80

after_success:
  - coveralls
  - ./bin/travis-upload.sh
# Add env var to detect it during build
env: TRAVIS=True
