[build-system]
requires = [
    "setuptools",
    "wheel",
    "cython>=0.29",
    "oldest-supported-numpy",
    "scipy>=1.0.0",
]
build-backend = "setuptools.build_meta"

[tool.black]
include = '\.pyi?$'
extend-exclude = '''
^/mars/(_version.py|lib/tblib/.*)
'''
