# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mars/serialize/tests/testser.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mars.serialize.protos import value_pb2 as mars_dot_serialize_dot_protos_dot_value__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mars/serialize/tests/testser.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"mars/serialize/tests/testser.proto\x1a!mars/serialize/protos/value.proto\"r\n\x08Node1Def\x12\t\n\x01\x61\x18\x01 \x01(\t\x12\t\n\x01\x62\x18\x02 \x01(\x05\x12\x11\n\x01\x63\x18\x03 \x01(\x0b\x32\x06.Value\x12\x14\n\x01\x64\x18\x04 \x01(\x0b\x32\t.Node2Def\x12\x11\n\x01\x65\x18\x05 \x03(\x0b\x32\x06.Value\x12\x14\n\x01\x66\x18\x06 \x03(\x0b\x32\t.Node1Def\"D\n\x08Node2Def\x12\x11\n\x01\x61\x18\x01 \x01(\x0b\x32\x06.Value\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x05\x12\n\n\x02id\x18\x04 \x01(\t\"E\n\x08Node3Def\x12\x17\n\x02n1\x18\x01 \x01(\x0b\x32\t.Node1DefH\x00\x12\x17\n\x02n2\x18\x02 \x01(\x0b\x32\t.Node2DefH\x00\x42\x07\n\x05value\"b\n\x08Node4Def\x12!\n\x04\x61ttr\x18\x01 \x03(\x0b\x32\x13.Node4Def.AttrEntry\x1a\x33\n\tAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x15\n\x05value\x18\x02 \x01(\x0b\x32\x06.Value:\x02\x38\x01\x62\x06proto3')
  ,
  dependencies=[mars_dot_serialize_dot_protos_dot_value__pb2.DESCRIPTOR,])




_NODE1DEF = _descriptor.Descriptor(
  name='Node1Def',
  full_name='Node1Def',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='Node1Def.a', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='Node1Def.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c', full_name='Node1Def.c', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='d', full_name='Node1Def.d', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='e', full_name='Node1Def.e', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f', full_name='Node1Def.f', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=187,
)


_NODE2DEF = _descriptor.Descriptor(
  name='Node2Def',
  full_name='Node2Def',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='Node2Def.a', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='Node2Def.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='Node2Def.data', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='Node2Def.id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=257,
)


_NODE3DEF = _descriptor.Descriptor(
  name='Node3Def',
  full_name='Node3Def',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n1', full_name='Node3Def.n1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n2', full_name='Node3Def.n2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='Node3Def.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=259,
  serialized_end=328,
)


_NODE4DEF_ATTRENTRY = _descriptor.Descriptor(
  name='AttrEntry',
  full_name='Node4Def.AttrEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Node4Def.AttrEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Node4Def.AttrEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=428,
)

_NODE4DEF = _descriptor.Descriptor(
  name='Node4Def',
  full_name='Node4Def',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attr', full_name='Node4Def.attr', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NODE4DEF_ATTRENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=428,
)

_NODE1DEF.fields_by_name['c'].message_type = mars_dot_serialize_dot_protos_dot_value__pb2._VALUE
_NODE1DEF.fields_by_name['d'].message_type = _NODE2DEF
_NODE1DEF.fields_by_name['e'].message_type = mars_dot_serialize_dot_protos_dot_value__pb2._VALUE
_NODE1DEF.fields_by_name['f'].message_type = _NODE1DEF
_NODE2DEF.fields_by_name['a'].message_type = mars_dot_serialize_dot_protos_dot_value__pb2._VALUE
_NODE3DEF.fields_by_name['n1'].message_type = _NODE1DEF
_NODE3DEF.fields_by_name['n2'].message_type = _NODE2DEF
_NODE3DEF.oneofs_by_name['value'].fields.append(
  _NODE3DEF.fields_by_name['n1'])
_NODE3DEF.fields_by_name['n1'].containing_oneof = _NODE3DEF.oneofs_by_name['value']
_NODE3DEF.oneofs_by_name['value'].fields.append(
  _NODE3DEF.fields_by_name['n2'])
_NODE3DEF.fields_by_name['n2'].containing_oneof = _NODE3DEF.oneofs_by_name['value']
_NODE4DEF_ATTRENTRY.fields_by_name['value'].message_type = mars_dot_serialize_dot_protos_dot_value__pb2._VALUE
_NODE4DEF_ATTRENTRY.containing_type = _NODE4DEF
_NODE4DEF.fields_by_name['attr'].message_type = _NODE4DEF_ATTRENTRY
DESCRIPTOR.message_types_by_name['Node1Def'] = _NODE1DEF
DESCRIPTOR.message_types_by_name['Node2Def'] = _NODE2DEF
DESCRIPTOR.message_types_by_name['Node3Def'] = _NODE3DEF
DESCRIPTOR.message_types_by_name['Node4Def'] = _NODE4DEF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Node1Def = _reflection.GeneratedProtocolMessageType('Node1Def', (_message.Message,), dict(
  DESCRIPTOR = _NODE1DEF,
  __module__ = 'mars.serialize.tests.testser_pb2'
  # @@protoc_insertion_point(class_scope:Node1Def)
  ))
_sym_db.RegisterMessage(Node1Def)

Node2Def = _reflection.GeneratedProtocolMessageType('Node2Def', (_message.Message,), dict(
  DESCRIPTOR = _NODE2DEF,
  __module__ = 'mars.serialize.tests.testser_pb2'
  # @@protoc_insertion_point(class_scope:Node2Def)
  ))
_sym_db.RegisterMessage(Node2Def)

Node3Def = _reflection.GeneratedProtocolMessageType('Node3Def', (_message.Message,), dict(
  DESCRIPTOR = _NODE3DEF,
  __module__ = 'mars.serialize.tests.testser_pb2'
  # @@protoc_insertion_point(class_scope:Node3Def)
  ))
_sym_db.RegisterMessage(Node3Def)

Node4Def = _reflection.GeneratedProtocolMessageType('Node4Def', (_message.Message,), dict(

  AttrEntry = _reflection.GeneratedProtocolMessageType('AttrEntry', (_message.Message,), dict(
    DESCRIPTOR = _NODE4DEF_ATTRENTRY,
    __module__ = 'mars.serialize.tests.testser_pb2'
    # @@protoc_insertion_point(class_scope:Node4Def.AttrEntry)
    ))
  ,
  DESCRIPTOR = _NODE4DEF,
  __module__ = 'mars.serialize.tests.testser_pb2'
  # @@protoc_insertion_point(class_scope:Node4Def)
  ))
_sym_db.RegisterMessage(Node4Def)
_sym_db.RegisterMessage(Node4Def.AttrEntry)


_NODE4DEF_ATTRENTRY._options = None
# @@protoc_insertion_point(module_scope)
