# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mars/serialize/protos/fusechunk.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mars.serialize.protos import value_pb2 as mars_dot_serialize_dot_protos_dot_value__pb2
from mars.serialize.protos import dataframe_pb2 as mars_dot_serialize_dot_protos_dot_dataframe__pb2
from mars.serialize.protos import tensor_pb2 as mars_dot_serialize_dot_protos_dot_tensor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mars/serialize/protos/fusechunk.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n%mars/serialize/protos/fusechunk.proto\x1a!mars/serialize/protos/value.proto\x1a%mars/serialize/protos/dataframe.proto\x1a\"mars/serialize/protos/tensor.proto\"\xf3\x02\n\x0c\x46useChunkDef\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x11\n\x05index\x18\x02 \x03(\rB\x02\x10\x01\x12\r\n\x05shape\x18\x03 \x03(\x03\x12\x12\n\x02op\x18\x04 \x01(\x0b\x32\x06.Value\x12\x0e\n\x06\x63\x61\x63hed\x18\x05 \x01(\x08\x12(\n\x08\x63omposed\x18\x07 \x03(\x0b\x32\x16.FuseChunkDef.ChunkDef\x12\x1c\n\x0c\x65xtra_params\x18\x08 \x01(\x0b\x32\x06.Value\x12\n\n\x02id\x18\t \x01(\t\x1a\xbb\x01\n\x08\x43hunkDef\x12\'\n\x0ctensor_chunk\x18\x01 \x01(\x0b\x32\x0f.TensorChunkDefH\x00\x12%\n\x0bindex_chunk\x18\x02 \x01(\x0b\x32\x0e.IndexChunkDefH\x00\x12\'\n\x0cseries_chunk\x18\x03 \x01(\x0b\x32\x0f.SeriesChunkDefH\x00\x12-\n\x0f\x64\x61taframe_chunk\x18\x04 \x01(\x0b\x32\x12.DataFrameChunkDefH\x00\x42\x07\n\x05\x63hunkb\x06proto3')
  ,
  dependencies=[mars_dot_serialize_dot_protos_dot_value__pb2.DESCRIPTOR,mars_dot_serialize_dot_protos_dot_dataframe__pb2.DESCRIPTOR,mars_dot_serialize_dot_protos_dot_tensor__pb2.DESCRIPTOR,])




_FUSECHUNKDEF_CHUNKDEF = _descriptor.Descriptor(
  name='ChunkDef',
  full_name='FuseChunkDef.ChunkDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensor_chunk', full_name='FuseChunkDef.ChunkDef.tensor_chunk', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index_chunk', full_name='FuseChunkDef.ChunkDef.index_chunk', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='series_chunk', full_name='FuseChunkDef.ChunkDef.series_chunk', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataframe_chunk', full_name='FuseChunkDef.ChunkDef.dataframe_chunk', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='chunk', full_name='FuseChunkDef.ChunkDef.chunk',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=336,
  serialized_end=523,
)

_FUSECHUNKDEF = _descriptor.Descriptor(
  name='FuseChunkDef',
  full_name='FuseChunkDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='FuseChunkDef.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='FuseChunkDef.index', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='FuseChunkDef.shape', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op', full_name='FuseChunkDef.op', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cached', full_name='FuseChunkDef.cached', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='composed', full_name='FuseChunkDef.composed', index=5,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra_params', full_name='FuseChunkDef.extra_params', index=6,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='FuseChunkDef.id', index=7,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FUSECHUNKDEF_CHUNKDEF, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=523,
)

_FUSECHUNKDEF_CHUNKDEF.fields_by_name['tensor_chunk'].message_type = mars_dot_serialize_dot_protos_dot_tensor__pb2._TENSORCHUNKDEF
_FUSECHUNKDEF_CHUNKDEF.fields_by_name['index_chunk'].message_type = mars_dot_serialize_dot_protos_dot_dataframe__pb2._INDEXCHUNKDEF
_FUSECHUNKDEF_CHUNKDEF.fields_by_name['series_chunk'].message_type = mars_dot_serialize_dot_protos_dot_dataframe__pb2._SERIESCHUNKDEF
_FUSECHUNKDEF_CHUNKDEF.fields_by_name['dataframe_chunk'].message_type = mars_dot_serialize_dot_protos_dot_dataframe__pb2._DATAFRAMECHUNKDEF
_FUSECHUNKDEF_CHUNKDEF.containing_type = _FUSECHUNKDEF
_FUSECHUNKDEF_CHUNKDEF.oneofs_by_name['chunk'].fields.append(
  _FUSECHUNKDEF_CHUNKDEF.fields_by_name['tensor_chunk'])
_FUSECHUNKDEF_CHUNKDEF.fields_by_name['tensor_chunk'].containing_oneof = _FUSECHUNKDEF_CHUNKDEF.oneofs_by_name['chunk']
_FUSECHUNKDEF_CHUNKDEF.oneofs_by_name['chunk'].fields.append(
  _FUSECHUNKDEF_CHUNKDEF.fields_by_name['index_chunk'])
_FUSECHUNKDEF_CHUNKDEF.fields_by_name['index_chunk'].containing_oneof = _FUSECHUNKDEF_CHUNKDEF.oneofs_by_name['chunk']
_FUSECHUNKDEF_CHUNKDEF.oneofs_by_name['chunk'].fields.append(
  _FUSECHUNKDEF_CHUNKDEF.fields_by_name['series_chunk'])
_FUSECHUNKDEF_CHUNKDEF.fields_by_name['series_chunk'].containing_oneof = _FUSECHUNKDEF_CHUNKDEF.oneofs_by_name['chunk']
_FUSECHUNKDEF_CHUNKDEF.oneofs_by_name['chunk'].fields.append(
  _FUSECHUNKDEF_CHUNKDEF.fields_by_name['dataframe_chunk'])
_FUSECHUNKDEF_CHUNKDEF.fields_by_name['dataframe_chunk'].containing_oneof = _FUSECHUNKDEF_CHUNKDEF.oneofs_by_name['chunk']
_FUSECHUNKDEF.fields_by_name['op'].message_type = mars_dot_serialize_dot_protos_dot_value__pb2._VALUE
_FUSECHUNKDEF.fields_by_name['composed'].message_type = _FUSECHUNKDEF_CHUNKDEF
_FUSECHUNKDEF.fields_by_name['extra_params'].message_type = mars_dot_serialize_dot_protos_dot_value__pb2._VALUE
DESCRIPTOR.message_types_by_name['FuseChunkDef'] = _FUSECHUNKDEF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FuseChunkDef = _reflection.GeneratedProtocolMessageType('FuseChunkDef', (_message.Message,), dict(

  ChunkDef = _reflection.GeneratedProtocolMessageType('ChunkDef', (_message.Message,), dict(
    DESCRIPTOR = _FUSECHUNKDEF_CHUNKDEF,
    __module__ = 'mars.serialize.protos.fusechunk_pb2'
    # @@protoc_insertion_point(class_scope:FuseChunkDef.ChunkDef)
    ))
  ,
  DESCRIPTOR = _FUSECHUNKDEF,
  __module__ = 'mars.serialize.protos.fusechunk_pb2'
  # @@protoc_insertion_point(class_scope:FuseChunkDef)
  ))
_sym_db.RegisterMessage(FuseChunkDef)
_sym_db.RegisterMessage(FuseChunkDef.ChunkDef)


_FUSECHUNKDEF.fields_by_name['index']._options = None
# @@protoc_insertion_point(module_scope)
