name: Mars CD for DockerHub

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        shell: bash
        env:
          DOCKER_ORG: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          source ./ci/reload-env.sh
          bash bin/kube-image-tool.sh -o "$DOCKER_ORG" -t "$GIT_TAG" build
          docker push "$DOCKER_ORG/mars:$GIT_TAG"
