name: Mars CD for DockerHub

on:
  push:
    branches:
      - master
      - main
      - 'v*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        shell: bash
        env:
          DOCKER_ORG: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          source ./ci/reload-env.sh
          if [[ "$DOCKER_ORG" == "marsuploader" ]]; then
            export DOCKER_ORG="marsproject"
          fi
          if [[ -n "$GIT_TAG" ]]; then
            export IMAGE_TAG="$GIT_TAG"
          else
            export IMAGE_TAG="nightly-$GIT_BRANCH"
          fi
          bash bin/kube-image-tool.sh -o "$DOCKER_ORG" -t "$IMAGE_TAG" build
          docker push "$DOCKER_ORG/mars:$IMAGE_TAG"
